payara/Payara-Community-Documentation

docs/modules/ROOT/pages/documentation/payara-server/app-deployment/descriptor-elements.adoc, docs/modules/ROOT/pages/documentation/payara-server/notification-service/notifiers/xmpp-notifier.adoc, docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/virtual-servers.adoc, docs/modules/ROOT/pages/documentation/user-guides/monitoring/monitoring-console.adoc, docs/modules/ROOT/pages/release-notes/release-notes-151.adoc, docs/modules/ROOT/pages/release-notes/release-notes-153.adoc, docs/modules/ROOT/pages/release-notes/release-notes-173.adoc
Fixes some xref words where a word **link** in plain text was incorrectly converted to **xref**.
I used this script to replace all occurrences (finds all "xref" strings followed by something else than a colon or those that are at the end of the line and replaces with "link"):
```
find . -type f -name "*.adoc" -print0 | xargs -0 sed -i'' -e 's/xref\([^:]\|$\)/link\1/g'
```
=> Fixed wrong xref words

docs/modules/ROOT/pages/documentation/payara-server/h2/h2.adoc
A copy of https://github.com/payara/Payara-Server-Documentation/pull/734 to update the already released 5.201 docs.
=> Derby DB removed (for 5.201 branch)

docs/modules/ROOT/pages/general-info/supported-platforms.adoc
To clarify that we support all OpenJDK-based JVMs
=> Support OpenJDK-based JVMs

docs/modules/ROOT/pages/documentation/microprofile/openapi.adoc
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>
=> FISH-128 Documentation for OpenAPI does not include APIs from jars within a war

docs/modules/ROOT/pages/documentation/payara-server/h2/h2.adoc
Replaces #62 to document how to connect to the H2 DBs in Payara Server with an SQL manager to execute SQL scripts or view the contents in the tables.
=> How to connect to H2 with an SQL manager

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/documentation/ecosystem/docker-images.adoc, docs/modules/ROOT/pages/documentation/ecosystem/docker-micro-usage.adoc, docs/modules/ROOT/pages/documentation/ecosystem/docker-server-usage.adoc
1: Transfer of the readme files of the archived Github repo containing Docker Image usage.
This is the basis to start improved and updated Payara Docker Image usage.
=> Docker Image documentation; updated and transferred from separate repository Readme

.gitignore, local-playbook.yml, package.json
NPM scripts added to run the documentation locally for review.
Run `npm start` to preview the docs locally. The docs will update when modified (although it takes a while, antora doesn't have hot reload by default).
Signed-off-by: Matthew Gill <matthew.gill@live.co.uk>
=> Add documentation preview scripts

docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
Introduction of a custom special property to disable the verification of the standard JWT authentication token verification of the type (`typ`) claim to make Payara compatible with most modern third-party token issuers.
=> FISH-651 Documented new changes for disabling JWT type verification

docs/modules/ROOT/pages/documentation/payara-server/app-deployment/deployment-descriptors.adoc
Antora has no global variable replacement for code blocks, meaning it has to be done strictly above the code block.
Enteprise PR: https://github.com/payara/Payara-Enterprise-Documentation/pull/84
=> SERV-502 Variable replacement in code example is not working

docs/modules/ROOT/pages/documentation/microprofile/jwt.adoc
Documented the improvement contributed in this community PR: https://github.com/payara/Payara/pull/5062/
=> Documented MP JWT Public Key Cache TTL

docs/modules/ROOT/pages/documentation/microprofile/config/directory.adoc
Match directory config source docs to current functionality, as https://github.com/payara/Payara/pull/5007 has been merged. :tada: 
This doc change aligns the docs with the new implementation of the directory config source for MicroProfile Config API.
Please review and feel free to change to adapt language, conventions etc.
A former pull request #114 has implemented large parts of this, so this is just an update.
=> FISH-788: update docs for directory config source

docs/modules/ROOT/pages/documentation/payara-server/ejb/persistent-timers.adoc
Timers can now be migrated from live instances.
=> FISH-105 Document change in migrate timers

docs/modules/ROOT/pages/documentation/extensions/notifiers/snmp-notifier.adoc, docs/modules/ROOT/pages/documentation/extensions/notifiers/xmpp-notifier.adoc, docs/modules/ROOT/pages/documentation/payara-server/admin-console/auditing-service.adoc, docs/modules/ROOT/pages/documentation/payara-server/health-check-service/asadmin-commands.adoc
Title.
Links to: https://github.com/payara/Payara/pull/5155, https://github.com/payara/Payara-Enterprise/pull/324, https://github.com/payara/Payara/pull/5155, https://github.com/payara/Notifiers/pull/15, https://github.com/payara/Notifiers/pull/16
=> FISH-1171 FISH-1172 FISH-1181 FISH-1182 Enabled No Longer Mandatory and Fix Conflicting Param Names

docs/modules/ROOT/pages/documentation/ecosystem/maven-plugin.adoc
The systemProperties configuration in the bundle goal is not present in the documentation, even if it is available in the Mojo https://github.com/payara/ecosystem-maven/blob/master/payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/BundleMojo.java#L135
This PR update the documentation accordingly.
=> Add systemProperties to bundle goal documentation

docs/modules/ROOT/pages/jakartaee-certification/6.2021.1.Alpha1/tck-results-full-6.2021.1.Alpha1.adoc
Download URL is pointing to website, it should be pointing to maven central as there is no download link for 6 on the website.
=> Update download link to maven central

docs/modules/ROOT/pages/documentation/payara-server/jcache/jcache-annotations.adoc, docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc
Current links lead to ignite project, but uses the old incubator address, which has to redirect. This update links directly to the current address.
=> Update jcache javadoc links

docs/modules/ROOT/pages/documentation/payara-server/server-configuration/ssl-certificates.adoc
Updated Additional Keystore information to be accurate with delimiter changes.
Community PR: https://github.com/payara/Payara/pull/5395
=> FISH-5693 Updated multiple keystore delimiter to be OS dependent

docs/modules/ROOT/pages/release-notes/release-notes-2020-2.adoc, docs/modules/ROOT/pages/release-notes/release-notes-2021-6.adoc
which mysteriously disappeared since the previous release
Plus added FISH-1332 to 5.2020.2 release notes which was missed when it was fixed.
=> Added missing release notes for 5.2021.6

docs/modules/ROOT/pages/security/security-fix-list.adoc
Adds the CVE and fix information for [CVE-2021-40690](https://nvd.nist.gov/vuln/detail/CVE-2021-40690#vulnCurrentDescriptionTitle)
=> FISH-5811 Upgrade Santuario to version 2.2.3

docs/modules/ROOT/pages/documentation/payara-micro/asadmin/pre-and-post-boot-scripts.adoc
Community PR: https://github.com/payara/Payara/pull/5589
Commit 3c5fbbbdd2ee70767f13ccb20fec8f8c1b475418 is fixing a broken link I noticed on this page and not related to the documentation of FISH-5974.
=> FISH-5974 Specify system-property with Double Quotes in preboot-command File

docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc
Tested what variables I can use.
* MP Config Properties (`${MPCONFIG=payara.security.openid.clientId`)
* Expression Language (`#{testBean.clientId}`)
* Password Aliases 
* Environment Variables / System Properties
=> FISH-5748 Alter OpenID Connect Doc

docs/modules/ROOT/pages/documentation/payara-server/deployment-groups/asadmin-commands.adoc
I couldn't find any documentation for the cluster commands or instance commands
=> FISH-898 Add documentation for timeout option

docs/modules/ROOT/pages/security/security-fix-list.adoc
Title. In reference to https://nvd.nist.gov/vuln/detail/CVE-2018-25032
=> FISH-6242 Document Update Docker Images for ZLib CVE-2018-25032
