payara/Payara-Community-Documentation

docs/modules/ROOT/pages/documentation/microprofile/rest-client.adoc

Replica of https://github.com/payara/Payara-Server-Documentation/pull/737

APPSERV-61 Rest Client 1.4

---

docs/modules/ROOT/pages/release-notes/release-notes-201.adoc

Fixes typos and community contributor links

Fix typos in release notes

---

docs/modules/ROOT/pages/release-notes/release-notes-201.adoc

Fix release notes

---

docs/modules/ROOT/pages/documentation/microprofile/config.adoc

In connection with payara/Payara#4614

APPSERV-114 adds section on added caching

---

docs/modules/ROOT/pages/documentation/microprofile/config.adoc
docs/modules/ROOT/pages/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.adoc

Original PR: payara/Payara#4584
Copy of https://github.com/payara/Payara-Server-Documentation/pull/724

APPSERV-20 Document new payara expression config source

---

docs/modules/ROOT/pages/documentation/user-guides/monitoring/monitoring-console.adoc

In connection with: payara/monitoring-console#8.
A copy of https://github.com/payara/Payara-Server-Documentation/pull/738

APPSERV-146 adds paragraph on bookmarkable URLs

---

docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/misc-commands.adoc
docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/network-listeners.adoc

In connection with https://github.com/payara/Payara/pull/4693

APPSERV-152 Adds section on the restart-http-listeners command

---

docs/modules/ROOT/pages/schemas/README.adoc

Already in 5.2020.2, porting to master

Fix links to schemas

---

docs/modules/ROOT/pages/documentation/microprofile/README.adoc
docs/modules/ROOT/pages/documentation/microprofile/faulttolerance.adoc
docs/modules/ROOT/pages/release-notes/README.adoc

Small updates to maintain version consistency

Minor fixes to replace 5.202 versioning

---

docs/modules/ROOT/pages/documentation/payara-server/asadmin-commands/auto-naming.adoc

To make it easier to find when searching for "dynamic"

Added "dynamic" keyword for autonaming

---

docs/modules/ROOT/pages/documentation/payara-micro/appendices/cmd-line-opts.adoc
docs/modules/ROOT/pages/documentation/payara-micro/configuring/config-sys-props.adoc

Source code added in: https://github.com/payara/Payara/pull/4739

FISH-205 Document Dynamic Logging

---

docs/modules/ROOT/pages/documentation/payara-server/system-properties.adoc

Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

FISH-256 System property to enable jakarta.* application transformation

---

docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/request-tracing-service.adoc
docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc
docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/usage.adoc

Main PR: https://github.com/payara/Payara/pull/4820

FISH-244 Document Tracing of Remote EJBs

---

docs/modules/ROOT/nav.adoc

Backporting https://github.com/payara/Payara-Community-Documentation/pull/59 to a released version

Link 'Tracing remote EJBs' from the navigation menu

---

docs/modules/ROOT/pages/documentation/user-guides/monitoring/monitoring-console.adoc

... to reflect the more integrated nature of MC
In connection with https://github.com/payara/Payara-Enterprise/pull/154
I removed the enterprise relevant changes from this PR

FISH-277 Updates Monitoring Console Manual Intro Sections

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.2/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.2/tck-results-full-5.2020.2.adoc
docs/modules/ROOT/pages/jakartaee-certification/README.adoc

Needs to be merged to 5.2020.3, 5.2020.4 and master branches too.

Added 5.2020.2 TCK results

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.2/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.2/tck-results-full-5.2020.2.adoc
docs/modules/ROOT/pages/jakartaee-certification/README.adoc

Copied from the 5.2020.2 branch (PR #63).

TCK summary for 5.2020.2

---

docs/modules/ROOT/pages/documentation/payara-server/app-deployment/deployment-descriptors.adoc
docs/modules/ROOT/pages/documentation/payara-server/jdbc/log-jdbc-calls.adoc

Payara Server PR payara/payara#4890

FISH-154 Document log-jdbc-calls now available via asadmin and payara-resources.xml

---

docs/modules/ROOT/pages/documentation/payara-server/logging/json-formatter.adoc

FISH-141 Support Additional Fields with LogRecord when using JsonLogFormatter

---

docs/modules/ROOT/pages/documentation/payara-server/server-configuration/jvm-options.adoc

Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

FISH-508 Add section on deleting JVM options

---

docs/modules/ROOT/pages/documentation/payara-server/system-properties.adoc

Jakarta EE transformer was not released in 5.2020.4

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/usage.adoc

Comments made on Enterprise port PR: https://github.com/payara/Payara-Enterprise-Documentation/pull/55

FISH-244 Additional review comments

---

docs/modules/ROOT/pages/release-notes/README.adoc

In addition to https://github.com/payara/Payara-Community-Documentation/pull/80

5.2020.5 release notes

---

docs/modules/ROOT/nav.adoc

Removed metrics checker from the docs

---

docs/modules/ROOT/pages/documentation/payara-server/jpa-cache-coordination.adoc

Wasn't valid according to the XSD schema

Fix of example code

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.6/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.6/tck-results-full-5.2020.6.adoc

FISH-707 add 5.2020.6 Jakarta TCK results

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.6/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.6/tck-results-web-5.2020.6.adoc

Publish web profile Jakarta TCK results for filing for Web Profile Certification

FISH-495 Web Profile Certification

---

docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-remote.adoc

See PR https://github.com/payara/ecosystem-arquillian-connectors/pull/94

FISH-784 added documentation for ignoreCertificates arquillian connector property

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.7/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2020.7/tck-results-full-5.2020.7.adoc

As title says, results for the Jakarta EE 8 TCK against community full profile

[FISH-807] - Community Full Jakarta EE results

---

docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-micro-managed.adoc
docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-embedded.adoc
docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-managed.adoc
docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-remote.adoc

Fixes: https://github.com/payara/Payara-Community-Documentation/issues/45

SERV-542 Examples shown in the arquillian containers not working

---

docs/modules/ROOT/pages/documentation/payara-server/jaxws/README.adoc
docs/modules/ROOT/pages/documentation/payara-server/jbatch/jbatch.adoc
docs/modules/ROOT/pages/documentation/payara-server/jcache/jcache.adoc
docs/modules/ROOT/pages/documentation/payara-server/server-configuration/var-substitution/README.adoc

Additional links so that it doesn't appear we have no detailed documentation.

Additional links

---

docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/release-notes/README.adoc
docs/modules/ROOT/pages/release-notes/release-notes-2021-1.adoc

Release Notes for Payara 5.2021.1 Community Edition Release
TCK results will come later as a separate PR

[FISH-1034] - Payara 5.2021.1 Release Notes

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.1/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.1/tck-results-full-5.2021.1.adoc
docs/modules/ROOT/pages/jakartaee-certification/README.adoc

Jakarta EE TCK Results for Payara 5.2021.1 Community Edition
Pending confirmation of a potential bug before merge can be made

[FISH-1038] - Community 5.2021.1 TCK Results

---

docs/modules/ROOT/pages/documentation/payara-server/server-configuration/var-substitution/types-of-variables.adoc

Adding missing documentation for payara/Payara#5089

FISH-992 document default value option in variable substitution

---

docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.2/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.2/tck-results-full-5.2021.2.adoc
docs/modules/ROOT/pages/release-notes/README.adoc
docs/modules/ROOT/pages/release-notes/release-notes-2021-2.adoc

[FISH-1122] - Payara 5.2021.2 Release Notes

---

docs/modules/ROOT/pages/documentation/ecosystem/cloud-connectors/README.adoc
docs/modules/ROOT/pages/documentation/ecosystem/gradle-plugin.adoc
docs/modules/ROOT/pages/documentation/ecosystem/maven-plugin.adoc
docs/modules/ROOT/pages/documentation/ecosystem/security-connectors.adoc
docs/modules/ROOT/pages/documentation/payara-micro/maven/maven.adoc
docs/modules/ROOT/pages/documentation/payara-server/README.adoc
docs/modules/ROOT/pages/documentation/payara-server/docker/docker-nodes.adoc
docs/modules/ROOT/pages/documentation/payara-server/hazelcast/using-hazelcast.adoc

Plus a couple of minor fixes to improve readability

Improvements on attribute substitution for current platform version

---

docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/protocols/ssl-options.adoc

Signed-off-by: Matthew Gill <matthew.gill@live.co.uk>

FISH-1021 Document HSTS Configuration Options

---

README.adoc
docs/antora.yml

To include some fixes from v5.2021.2

Merge v5.2021.2

---

docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.3/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.3/tck-results-full-5.2021.3.adoc
docs/modules/ROOT/pages/release-notes/README.adoc
docs/modules/ROOT/pages/release-notes/release-notes-2021-3.adoc

Payara 5.2021.3 Release Notes

---

docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.4/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.4/tck-results-full-5.2021.4.adoc
docs/modules/ROOT/pages/release-notes/README.adoc
docs/modules/ROOT/pages/release-notes/release-notes-2021-4.adoc

[FISH-1400] Payara 5.2021.4 Release Notes

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/6.2021.1.Alpha1/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/6.2021.1.Alpha1/tck-results-full-6.2021.1.Alpha1.adoc

Master branch PR: https://github.com/payara/Payara-Community-Documentation/pull/173

FISH-1501 Jakarta 9.1 TCK result

---

docs/modules/ROOT/pages/documentation/ecosystem/docker-images/server-image-overview.adoc

PR https://github.com/payara/Payara/pull/5328

FISH-371 Documentation 

---

docs/modules/ROOT/pages/documentation/ecosystem/docker-images/server-image-overview.adoc

FISH-371 changes

---

docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/release-notes/README.adoc
docs/modules/ROOT/pages/release-notes/release-notes-2021-5.adoc

5.2021.5 Release Notes

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.5/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.5/tck-results-full-5.2021.5.adoc

Title
Additionally added a newline between Payara 6 and Payara 5 entries for to make it a little easier to read separate, will remove if not wanted

Community 5.2021.5 TCK Results

---

docs/modules/ROOT/pages/security/security.adoc

Simplified messaging around security section for better clarity

Security Section Rewording

---

docs/modules/ROOT/pages/documentation/payara-server/jcache/jcache-annotations.adoc
docs/modules/ROOT/pages/documentation/payara-server/request-tracing-service/tracing-remote-ejbs.adoc

There were missing double quotes in the sample code in tracing-remote-ejbs.adoc

Fix sample code tracing-remote-ejbs.adoc

---

docs/modules/ROOT/pages/documentation/microprofile/metrics/vendor-metrics.adoc
docs/modules/ROOT/pages/security/security-fix-list.adoc

Plus a fix in an unrelated code example

Added security fixes for the upcoming release

---

docs/modules/ROOT/pages/documentation/payara-server/server-configuration/http/protocols/http-options.adoc

HTTP Compression Level and Strategy documentation
Community PR: https://github.com/payara/Payara/pull/5407

FISH-376 Allow configuration details of HTTP GZIP compression

---

docs/modules/ROOT/pages/release-notes/release-notes-2021-6.adoc

which mysteriously disappeared since the previous release

Added missing release notes for 5.2021.6 into branch 5.2021.7

---

docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc

this is the documentation for the new property userClaimsFromIDToken  that enable to the the user information from ID Token

FISH-5725: doc for userClaimsFromIDToken property

---

docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc

Reverts payara/Payara-Community-Documentation#267
This needs to wait until after 5.33.0 is released.

Revert "FISH-5725: doc for userClaimsFromIDToken property"

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.9/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2021.9/tck-results-full-5.2021.9.adoc

Needs [Release Notes](https://github.com/payara/Payara-Community-Documentation/pull/269) merging.

5.2021.9 TCK Results

---

docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc

Adding doc for new property disableScopeValidation

FISH-386: scope validation property doc

---

docs/modules/ROOT/pages/documentation/microprofile/rest-client.adoc

Title.
Related PRs:
* https://github.com/payara/MicroProfile-TCK-Runners/pull/156
* https://github.com/payara/patched-src-jersey/pull/111
* https://github.com/payara/Payara/pull/5506

FISH-1519 Document MP Rest Client Proxy Config

---

docs/modules/ROOT/pages/documentation/payara-server/public-api/openid-connect-support.adoc

Document the new configuration, add note, that key may repeat.
Should be merged after #266.

Fish 5745 extra params raw

---

docs/modules/ROOT/pages/security/security-fix-list.adoc

Do not merge yet - let's wait if the CVE is evaluated.
If the CVE isn't evaluated before the next release, we can merge this PR, not worth to wait for the evaluation.

Vulnerability in H2 Console

---

docs/modules/ROOT/pages/documentation/ecosystem/arquillian-containers/payara-server-embedded.adoc

Main PR: https://github.com/payara/ecosystem-arquillian-connectors/pull/163
Signed-off-by: Andrew Pielage <pandrex247@hotmail.com>

FISH-778 Document Embedded Arquillian Server System Properties

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2022.1/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/5.2022.1/tck-results-full-5.2022.1.adoc
docs/modules/ROOT/pages/jakartaee-certification/6.2022.1.Alpha2/README.adoc
docs/modules/ROOT/pages/jakartaee-certification/6.2022.1.Alpha2/tck-results-full-6.2022.1.Alpha2.adoc
docs/modules/ROOT/pages/release-notes/README.adoc
docs/modules/ROOT/pages/release-notes/release-notes-2022-1.adoc

5.2022.1 release notes tck results

---

docs/modules/ROOT/nav.adoc

Updating the nav.adoc file was missed in https://github.com/payara/Payara-Community-Documentation/pull/261

FISH-230 Update Nav

---

docs/modules/ROOT/pages/documentation/payara-server/ejb/README.adoc

Community PR: https://github.com/payara/Payara/pull/5653

FISH 6027 - Remote EJB + JDK 17 does not work

---

LICENSE.md

Add EPL 2.0 license as agreed in the Jira ticket.

FISH-5841 add license

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/microprofile-certification/6.2022.1.Alpha2/README.adoc
docs/modules/ROOT/pages/microprofile-certification/6.2022.1.Alpha2/microprofile-5.0-tck-results-full-6.2022.1.Alpha2.adoc
docs/modules/ROOT/pages/microprofile-certification/6.2022.1.Alpha2/microprofile-5.0-tck-results-web-6.2022.1.Alpha2.adoc

Title.
Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

FISH-6334 Add MP 5.0 TCK results for 6.2022.1.Alpha2

---

docs/modules/ROOT/pages/documentation/ecosystem/docker-images/micro-image-overview.adoc
docs/modules/ROOT/pages/documentation/ecosystem/docker-images/server-image-overview.adoc

Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

FISH-6353 Document existence of JDK 17 Docker image

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/documentation/extensions/README.adoc
docs/modules/ROOT/pages/documentation/extensions/transformer/README.adoc
docs/modules/ROOT/pages/documentation/payara-server/system-properties.adoc

Signed-off-by: Andrew Pielage <andrew.pielage@payara.fish>

FISH-6034 Rework Jakarta Namespace Transformer into an Extension

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/microprofile-certification/6.2022.1.Alpha2/README.adoc
docs/modules/ROOT/pages/microprofile-certification/6.2022.1.Alpha2/microprofile-5.0-tck-results-full-6.2022.1.Alpha2.adoc
docs/modules/ROOT/pages/microprofile-certification/6.2022.1.Alpha2/microprofile-5.0-tck-results-web-6.2022.1.Alpha2.adoc

Backport of https://github.com/payara/Payara-Community-Documentation/pull/311

Payara 6.2022.1.Alpha2 MicroProfile 5 TCK Results (Backport)
